In [1]:
!mkdir -p pretrained
!wget -O pretrained/ram_swin_large_14m.pth \
https://huggingface.co/spaces/xinyu1205/recognize-anything/resolve/main/ram_swin_large_14m.pth

--2026-03-28 13:22:04--  https://huggingface.co/spaces/xinyu1205/recognize-anything/resolve/main/ram_swin_large_14m.pth
Resolving huggingface.co (huggingface.co)... 3.171.171.65, 3.171.171.128, 3.171.171.6, ...
Connecting to huggingface.co (huggingface.co)|3.171.171.65|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cas-bridge.xethub.hf.co/xet-bridge-us/63bf7dd982f7306d07531496/80b8ba98fae5aa1ded68e585bb8dcd2f1dfa308f3ac1d707430129f2e492744d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20260328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260328T132204Z&X-Amz-Expires=3600&X-Amz-Signature=603ec7973028fd0791d83131df9b10c5e51af8db5f57f60f1dc17ece63cabf6f&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27ram_swin_large_14m.pth%3B+filename%3D%22ram_swin_large_14m.pth%22%3B&x-amz-checksum-mode=ENABLED&x-id=GetObject&Expires=1774707724&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc3NDcwNzcyNH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82M2JmN2RkOTgyZjczMDZkMDc1MzE0OTYvODBiOGJhOThmYWU1YWExZGVkNjhlNTg1YmI4ZGNkMmYxZGZhMzA4ZjNhYzFkNzA3NDMwMTI5ZjJlNDkyNzQ0ZCoifV19&Signature=b--8HM8IJSVYVFlnO1RzmF3MKr3oFQmRkQ-O1Z2qIzClQFENqqGwbShoHqWikmnjypdMtnKZJC2M77aI-AK5l2i0P83Fy-THPTW0triddotEua04p6g4TQ4bV9twBThnufyk-kmnAXX4OQIl8IZQnZIQw78IPMMMH7LE35WtEx5qR%7ESPSDzX9IHLzzN%7EkNeDrfeaU8SUBtwxhOA9Lt0e9lDCS2Oh7eJeke2zs7oNwDUzzLA3OBrNHTmk6981Dxw5Uipei%7EzIpK1SUMUtVvyRfSEI6%7Ekm462M2D6NQH2lfFF5YG%7EHrn0A8T6v17P7MMo9nvm2BueXOxCFAzwIyc3NVA__&Key-Pair-Id=K2L8F4GPSG1IFC [following]
--2026-03-28 13:22:04--  https://cas-bridge.xethub.hf.co/xet-bridge-us/63bf7dd982f7306d07531496/80b8ba98fae5aa1ded68e585bb8dcd2f1dfa308f3ac1d707430129f2e492744d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20260328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260328T132204Z&X-Amz-Expires=3600&X-Amz-Signature=603ec7973028fd0791d83131df9b10c5e51af8db5f57f60f1dc17ece63cabf6f&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27ram_swin_large_14m.pth%3B+filename%3D%22ram_swin_large_14m.pth%22%3B&x-amz-checksum-mode=ENABLED&x-id=GetObject&Expires=1774707724&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc3NDcwNzcyNH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82M2JmN2RkOTgyZjczMDZkMDc1MzE0OTYvODBiOGJhOThmYWU1YWExZGVkNjhlNTg1YmI4ZGNkMmYxZGZhMzA4ZjNhYzFkNzA3NDMwMTI5ZjJlNDkyNzQ0ZCoifV19&Signature=b--8HM8IJSVYVFlnO1RzmF3MKr3oFQmRkQ-O1Z2qIzClQFENqqGwbShoHqWikmnjypdMtnKZJC2M77aI-AK5l2i0P83Fy-THPTW0triddotEua04p6g4TQ4bV9twBThnufyk-kmnAXX4OQIl8IZQnZIQw78IPMMMH7LE35WtEx5qR%7ESPSDzX9IHLzzN%7EkNeDrfeaU8SUBtwxhOA9Lt0e9lDCS2Oh7eJeke2zs7oNwDUzzLA3OBrNHTmk6981Dxw5Uipei%7EzIpK1SUMUtVvyRfSEI6%7Ekm462M2D6NQH2lfFF5YG%7EHrn0A8T6v17P7MMo9nvm2BueXOxCFAzwIyc3NVA__&Key-Pair-Id=K2L8F4GPSG1IFC
Resolving cas-bridge.xethub.hf.co (cas-bridge.xethub.hf.co)... 13.32.179.58, 13.32.179.6, 13.32.179.62, ...
Connecting to cas-bridge.xethub.hf.co (cas-bridge.xethub.hf.co)|13.32.179.58|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5625634877 (5.2G)
Saving to: ‘pretrained/ram_swin_large_14m.pth’

pretrained/ram_swin 100%[===================>]   5.24G   314MB/s    in 16s

2026-03-28 13:22:20 (338 MB/s) - ‘pretrained/ram_swin_large_14m.pth’ saved [5625634877/5625634877]

In [ ]:
!rm -r /kaggle/working/recognize-anything
%cd /kaggle/working

In [2]:
!pip install fairscale -q
!git clone https://github.com/ThinhSama234/image_tagging.git
%cd image_tagging
!pip install -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.3/266.3 kB 101.1 kB/s eta 0:00:0000:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for fairscale (pyproject.toml) ... done
Cloning into 'image_tagging'...
remote: Enumerating objects: 835, done.
remote: Counting objects: 100% (835/835), done.
remote: Compressing objects: 100% (394/394), done.
remote: Total 835 (delta 449), reused 813 (delta 430), pack-reused 0 (from 0)
Receiving objects: 100% (835/835), 34.84 MiB | 31.34 MiB/s, done.
Resolving deltas: 100% (449/449), done.
/kaggle/working/image_tagging
Collecting clip@ git+https://github.com/openai/CLIP.git (from -r requirements.txt (line 9))
  Cloning https://github.com/openai/CLIP.git to /tmp/pip-install-3ph371sn/clip_d1dc70f798c4454c8500109db9566c30
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git /tmp/pip-install-3ph371sn/clip_d1dc70f798c4454c8500109db9566c30
  Resolved https://github.com/openai/CLIP.git to commit d05afc436d78f1c48dc0dbf8e5980a9d471f35f6
  Preparing metadata (setup.py) ... done
Collecting timm==0.4.12 (from -r requirements.txt (line 1))
  Downloading timm-0.4.12-py3-none-any.whl.metadata (30 kB)
Collecting transformers<=4.55.4,>=4.25.1 (from -r requirements.txt (line 2))
  Downloading transformers-4.55.4-py3-none-any.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 3.0 MB/s eta 0:00:00
Collecting fairscale==0.4.4 (from -r requirements.txt (line 3))
  Downloading fairscale-0.4.4.tar.gz (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.4/235.4 kB 8.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycocoevalcap (from -r requirements.txt (line 4))
  Downloading pycocoevalcap-1.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (0.25.0+cu128)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (11.3.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (1.16.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (3.24.3)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2))
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (2.32.4)
Collecting tokenizers<0.22,>=0.21 (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2))
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (4.67.3)
Requirement already satisfied: pycocotools>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from pycocoevalcap->-r requirements.txt (line 4)) (2.0.11)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (2026.2.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->-r requirements.txt (line 5)) (1.3.5)
Collecting ftfy (from clip@ git+https://github.com/openai/CLIP.git->-r requirements.txt (line 9))
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->-r requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy->clip@ git+https://github.com/openai/CLIP.git->-r requirements.txt (line 9)) (0.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->-r requirements.txt (line 5)) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<=4.55.4,>=4.25.1->-r requirements.txt (line 2)) (2026.1.4)
Downloading timm-0.4.12-py3-none-any.whl (376 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.0/377.0 kB 15.8 MB/s eta 0:00:00
Downloading transformers-4.55.4-py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 91.2 MB/s eta 0:00:00:00:0100:01
Downloading pycocoevalcap-1.2-py3-none-any.whl (104.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.3/104.3 MB 18.6 MB/s eta 0:00:0000:0100:01
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 37.7 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 96.4 MB/s eta 0:00:00
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.7 MB/s eta 0:00:00
Building wheels for collected packages: fairscale, clip
  Building wheel for fairscale (pyproject.toml) ... done
  Created wheel for fairscale: filename=fairscale-0.4.4-py3-none-any.whl size=292934 sha256=4963d9c980728a9b4791b12bbbb0827df8345109988e24ff15f4cc0a28891472
  Stored in directory: /root/.cache/pip/wheels/c9/20/41/aa2b3bbf5be3e499093089cf636460d2111a2b3314ae0ebbc6
  Building wheel for clip (setup.py) ... done
  Created wheel for clip: filename=clip-1.0-py3-none-any.whl size=1369490 sha256=8d82a8b5163b979ec7c5e1bf0087519e59211e8c75008ed0fcb2717316d63339
  Stored in directory: /tmp/pip-ephem-wheel-cache-jkvnke0o/wheels/35/3e/df/3d24cbfb3b6a06f17a2bfd7d1138900d4365d9028aa8f6e92f
Successfully built fairscale clip
Installing collected packages: ftfy, pycocoevalcap, huggingface-hub, tokenizers, transformers, fairscale, timm, clip
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
  Attempting uninstall: fairscale
    Found existing installation: fairscale 0.4.13
    Uninstalling fairscale-0.4.13:
      Successfully uninstalled fairscale-0.4.13
  Attempting uninstall: timm
    Found existing installation: timm 1.0.25
    Uninstalling timm-1.0.25:
      Successfully uninstalled timm-1.0.25
Successfully installed clip-1.0 fairscale-0.4.4 ftfy-6.3.1 huggingface-hub-0.36.2 pycocoevalcap-1.2 timm-0.4.12 tokenizers-0.21.4 transformers-4.55.4

In [3]:
from ram.models import ram
from ram import inference_ram, inference_ram_openset
print("Done")

2026-03-28 13:23:33.670713: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774704213.869048      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774704213.930910      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774704214.431193      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774704214.431239      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774704214.431243      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774704214.431245      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Done

/usr/local/lib/python3.12/dist-packages/fairscale/experimental/nn/offload.py:19: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  return torch.cuda.amp.custom_fwd(orig_func)  # type: ignore
/usr/local/lib/python3.12/dist-packages/fairscale/experimental/nn/offload.py:30: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  return torch.cuda.amp.custom_bwd(orig_func)  # type: ignore

In [16]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
RAM_WEIGHTS_PATH = "/kaggle/working/pretrained/ram_swin_large_14m.pth"
model = ram(pretrained=RAM_WEIGHTS_PATH, image_size=384, vit='swin_l')
model = model.to(device)
model.eval()

BertLMHeadModel has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.

/encoder/layer/0/crossattention/self/query is tied
/encoder/layer/0/crossattention/self/key is tied
/encoder/layer/0/crossattention/self/value is tied
/encoder/layer/0/crossattention/output/dense is tied
/encoder/layer/0/crossattention/output/LayerNorm is tied
/encoder/layer/0/intermediate/dense is tied
/encoder/layer/0/output/dense is tied
/encoder/layer/0/output/LayerNorm is tied
/encoder/layer/1/crossattention/self/query is tied
/encoder/layer/1/crossattention/self/key is tied
/encoder/layer/1/crossattention/self/value is tied
/encoder/layer/1/crossattention/output/dense is tied
/encoder/layer/1/crossattention/output/LayerNorm is tied
/encoder/layer/1/intermediate/dense is tied
/encoder/layer/1/output/dense is tied
/encoder/layer/1/output/LayerNorm is tied
--------------
/kaggle/working/pretrained/ram_swin_large_14m.pth
--------------
load checkpoint from /kaggle/working/pretrained/ram_swin_large_14m.pth
vit: swin_l

RAM(
  (visual_encoder): SwinTransformer(
    (patch_embed): PatchEmbed(
      (proj): Conv2d(3, 192, kernel_size=(4, 4), stride=(4, 4))
      (norm): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
    )
    (pos_drop): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0): BasicLayer(
        dim=192, input_resolution=(96, 96), depth=2
        (blocks): ModuleList(
          (0): SwinTransformerBlock(
            dim=192, input_resolution=(96, 96), num_heads=6, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=192, window_size=(12, 12), num_heads=6
              (qkv): Linear(in_features=192, out_features=576, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=192, out_features=192, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): Identity()
            (norm2): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=192, out_features=768, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=768, out_features=192, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (1): SwinTransformerBlock(
            dim=192, input_resolution=(96, 96), num_heads=6, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=192, window_size=(12, 12), num_heads=6
              (qkv): Linear(in_features=192, out_features=576, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=192, out_features=192, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=192, out_features=768, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=768, out_features=192, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
        )
        (downsample): PatchMerging(
          input_resolution=(96, 96), dim=192
          (reduction): Linear(in_features=768, out_features=384, bias=False)
          (norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
      (1): BasicLayer(
        dim=384, input_resolution=(48, 48), depth=2
        (blocks): ModuleList(
          (0): SwinTransformerBlock(
            dim=384, input_resolution=(48, 48), num_heads=12, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=384, window_size=(12, 12), num_heads=12
              (qkv): Linear(in_features=384, out_features=1152, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=384, out_features=384, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=384, out_features=1536, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=1536, out_features=384, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (1): SwinTransformerBlock(
            dim=384, input_resolution=(48, 48), num_heads=12, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=384, window_size=(12, 12), num_heads=12
              (qkv): Linear(in_features=384, out_features=1152, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=384, out_features=384, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=384, out_features=1536, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=1536, out_features=384, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
        )
        (downsample): PatchMerging(
          input_resolution=(48, 48), dim=384
          (reduction): Linear(in_features=1536, out_features=768, bias=False)
          (norm): LayerNorm((1536,), eps=1e-05, elementwise_affine=True)
        )
      )
      (2): BasicLayer(
        dim=768, input_resolution=(24, 24), depth=18
        (blocks): ModuleList(
          (0): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (1): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (2): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (3): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (4): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (5): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (6): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (7): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (8): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (9): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (10): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (11): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (12): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=0, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (13): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=6, mlp_ratio=4.0
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              dim=768, window_size=(12, 12), num_heads=24
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath()
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (14): SwinTransformerBlock(
            dim=768, input_resolution=(24, 24), num_heads=24, window_size=12, shift_size=0, mlp_ratio=4.0

In [6]:
import os
import json
import torch
import pandas as pd
from PIL import Image
import torchvision.transforms as T
from tqdm import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
transform = T.Compose([
    T.Resize((384, 384)),
    T.ToTensor(),
])

# Parse label từ ADE20K JSON

In [75]:
def get_labels_from_json(json_path):
    with open(json_path, "r") as f:
        data = json.load(f)

    labels = set()

    # object labels
    for obj in data.get("objects", []):
        labels.add(obj["classTitle"].lower())

    # scene tags (optional)
    for tag in data.get("tags", []):
        if tag["name"] == "scene":
            for s in tag["value"].split(","):
                labels.add(s.strip().lower())

    return list(labels)

In [76]:
def normalize_label(label):
    return label.lower().strip()

def normalize_list(lst):
    return list(set([normalize_label(x) for x in lst]))

# Inference toàn bộ dataset + lưu CSV

# Tập val

In [73]:
IMG_DIR_VAL = "/kaggle/input/datasets/nguyenbon/ade20k/validation/img"
ANN_DIR_VAL = "/kaggle/input/datasets/nguyenbon/ade20k/validation/ann"

OUTPUT_CSV_VAL = "/kaggle/working/ram_results.csv"

In [79]:
results = []

image_files = [f for f in os.listdir(IMG_DIR_VAL) if f.endswith(".jpg")]

for fname in tqdm(image_files):
    img_path = os.path.join(IMG_DIR_VAL, fname)
    ann_path = os.path.join(ANN_DIR_VAL, fname + ".json")

    if not os.path.exists(ann_path):
        continue

    # ===== Load image =====
    try:
        img = Image.open(img_path).convert("RGB")
        img_tensor = transform(img).unsqueeze(0).to(device)
    except:
        continue

    # ===== Ground truth =====
    gt_labels = get_labels_from_json(ann_path)

    # ===== RAM inference =====
    with torch.no_grad():
        pred_tags = inference_ram_openset(img_tensor, model)

    # ===== Save result =====
    results.append({
        "image": fname,
        "gt": " | ".join(gt_labels),
        "pred": pred_tags 
    })

# ===== Save CSV =====
df = pd.DataFrame(results)
df.to_csv(OUTPUT_CSV_VAL, index=False)

print("Saved to:", OUTPUT_CSV_VAL)
df.head()

100%|██████████| 2000/2000 [05:25<00:00,  6.14it/s]

Saved to: /kaggle/working/ram_results.csv

,image,gt,pred
0,ADE_val_00001821.jpg,crosswalk | sidewalk | pole | balcony | roof |...,building | city | city street | daylight | fog...
1,ADE_val_00001471.jpg,button panel | top | extractor hood | bowl | h...,appliance | bureau | cabinet | cabinetry | cle...
2,ADE_val_00001003.jpg,wing | right leg | mountain | street light | t...,air field | plane | airport runway | arm | arm...
3,ADE_val_00000792.jpg,car | license plate | windshield | pole | side...,car | curb | park | road | stop sign | street ...
4,ADE_val_00001634.jpg,unclassified | television | window | light tro...,bed | bedroom | ceiling | floor | modern | roo...

# evaluate

In [35]:
df = pd.read_csv(OUTPUT_CSV_VAL)

def split_labels(s):
    if pd.isna(s) or s.strip() == "":
        return []
    
    return [
        x.strip().lower()        # bỏ space + normalize
        for x in s.split("|")
        if x.strip() != ""       # bỏ phần tử rỗng
    ]

df["gt_list"] = df["gt"].apply(split_labels)
df["pred_list"] = df["pred"].apply(split_labels)

df.head()

,image,gt,pred,gt_list,pred_list
0,ADE_val_00001821.jpg,roof | street | trash can | sky | sidewalk | s...,building | city | city street | daylight | fog...,"[roof, street, trash can, sky, sidewalk, sign,...","[building, city, city street, daylight, fog, f..."
1,ADE_val_00001471.jpg,light switch | chest of drawers | vent | butto...,appliance | bureau | cabinet | cabinetry | cle...,"[light switch, chest of drawers, vent, button ...","[appliance, bureau, cabinet, cabinetry, clean,..."
2,ADE_val_00001003.jpg,airplane | outdoor | left arm | sky | air_base...,air field | plane | airport runway | arm | arm...,"[airplane, outdoor, left arm, sky, air_base, c...","[air field, plane, airport runway, arm, army, ..."
3,ADE_val_00000792.jpg,car | roof | street | trash can | sky | sidewa...,car | curb | park | road | stop sign | street ...,"[car, roof, street, trash can, sky, sidewalk, ...","[car, curb, park, road, stop sign, street corn..."
4,ADE_val_00001634.jpg,door | television | wall recessed light | wall...,bed | bedroom | ceiling | floor | modern | roo...,"[door, television, wall recessed light, wall, ...","[bed, bedroom, ceiling, floor, modern, room, s..."

In [80]:
import pandas as pd
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

# =========================
# Utils
# =========================
def normalize_tag(tag):
    tag = tag.strip().lower()
    tag = tag.replace("_", " ")
    tag = " ".join(tag.split())
    return tag

def lemma_tag(tag):
    return " ".join([lemmatizer.lemmatize(w) for w in tag.split()])

def parse_pipe_tags(tag_str):
    # handle NaN
    if pd.isna(tag_str):
        return []

    return [t.strip() for t in tag_str.split("|") if t.strip() != ""]

# =========================
# Load data
# =========================
df = pd.read_csv("/kaggle/working/ram_results.csv")

# =========================
# Compute P/R
# =========================
tp, fp, fn = 0, 0, 0

for _, row in df.iterrows():
    gt_tags = parse_pipe_tags(row["gt"])
    pred_tags = parse_pipe_tags(row["pred"])

    gt_set = set([lemma_tag(normalize_tag(t)) for t in gt_tags])
    pred_set = set([lemma_tag(normalize_tag(t)) for t in pred_tags])

    # exact match trên synonym space
    inter = pred_set & gt_set

    tp += len(inter)
    fp += len(pred_set - gt_set)
    fn += len(gt_set - pred_set)

# =========================
# Final metrics
# =========================
precision = tp / (tp + fp + 1e-8)
recall = tp / (tp + fn + 1e-8)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Precision: 0.2581
Recall: 0.1842

In [72]:
df.head()

             file                                                 gt  pred
0  1000092795.jpg  enjoy | friend | garden | guy | hair | hand | ...   NaN
1    10002456.jpg  equipment | hat | machine | man | on top | ope...   NaN
2  1000268201.jpg  ascent | building | cabin | child | dress | en...   NaN
3  1000344755.jpg  building | clean_and_jerk | hat | jean | ladde...   NaN
4  1000366164.jpg  approach | camera | cook | cook food | food | ...   NaN

# Dataset Flickr-30k

In [15]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

import torch
from PIL import Image
import torchvision.transforms as T

import sng_parser

# NLP
import nltk
from nltk.corpus import stopwords, wordnet

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [17]:
csv_path = "/kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/results.csv"
image_dir = "/kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/flickr30k_images"

df = pd.read_csv(csv_path, sep="|")

# clean
df.columns = df.columns.str.strip()
df["image_name"] = df["image_name"].str.strip()
df["comment"] = df["comment"].str.strip()

df.head()

,image_name,comment_number,comment
0,1000092795.jpg,0,Two young guys with shaggy hair look at their ...
1,1000092795.jpg,1,"Two young , White males are outside near many ..."
2,1000092795.jpg,2,Two men in green shirts are standing in a yard .
3,1000092795.jpg,3,A man in a blue shirt standing in a garden .
4,1000092795.jpg,4,Two friends enjoy time spent together .

In [18]:
def parse_caption_to_tags(caption):
    try:
        graph = sng_parser.parse(caption)
    except:
        return []

    tags = []

    # entities
    for ent in graph["entities"]:
        tags.append(ent["lemma_head"])

    # relations (verbs / prepositions)
    for rel in graph["relations"]:
        tags.append(rel["lemma_relation"])

    return tags

In [19]:
def normalize_tags(tags):
    clean_tags = []

    for t in tags:
        t = t.lower().strip()

        # bỏ stopword
        if t in stop_words:
            continue

        clean_tags.append(t)

    return clean_tags

# Setup SceneGraphParser

In [ ]:
!pip install SceneGraphParser
!python -m spacy download en  # to use the parser for English

In [ ]:
!pip install spacy

In [5]:
import sng_parser
graph = sng_parser.parse('A woman is playing the piano in the room.')

In [14]:
from pprint import pprint
pprint(graph)

{'entities': [{'head': 'woman',
               'lemma_head': 'woman',
               'lemma_span': 'a woman',
               'modifiers': [{'dep': 'det', 'lemma_span': 'a', 'span': 'A'}],
               'span': 'A woman',
               'span_bounds': (0, 2),
               'type': 'unknown'},
              {'head': 'piano',
               'lemma_head': 'piano',
               'lemma_span': 'the piano',
               'modifiers': [{'dep': 'det',
                              'lemma_span': 'the',
                              'span': 'the'}],
               'span': 'the piano',
               'span_bounds': (4, 6),
               'type': 'unknown'},
              {'head': 'room',
               'lemma_head': 'room',
               'lemma_span': 'the room',
               'modifiers': [{'dep': 'det',
                              'lemma_span': 'the',
                              'span': 'the'}],
               'span': 'the room',
               'span_bounds': (7, 9),
               'type': 'scene'}],
 'relations': [{'lemma_relation': 'play',
                'object': 1,
                'relation': 'playing',
                'subject': 0},
               {'lemma_relation': 'in',
                'object': 2,
                'relation': 'in',
                'subject': 0}]}

In [20]:
def wordnet_map(tag):
    synsets = wordnet.synsets(tag)

    if len(synsets) == 0:
        return tag

    # lấy lemma đầu tiên
    return synsets[0].lemmas()[0].name()

In [21]:
image_tags = {}

for _, row in tqdm(df.iterrows(), total=len(df)):
    img = row["image_name"]
    caption = row["comment"]

    tags = parse_caption_to_tags(caption)
    tags = normalize_tags(tags)
    tags = [wordnet_map(t) for t in tags]

    if img not in image_tags:
        image_tags[img] = set()

    image_tags[img].update(tags)

100%|██████████| 158915/158915 [16:18<00:00, 162.42it/s]

In [22]:
gt_data = []

for img, tags in image_tags.items():
    gt_data.append({
        "file": img,
        "gt": " | ".join(sorted(tags))
    })

gt_df = pd.DataFrame(gt_data)
gt_df.head()

             file                                                 gt
0  1000092795.jpg  enjoy | friend | garden | guy | hair | hand | ...
1    10002456.jpg  equipment | hat | machine | man | on top | ope...
2  1000268201.jpg  ascent | building | cabin | child | dress | en...
3  1000344755.jpg  building | clean_and_jerk | hat | jean | ladde...
4  1000366164.jpg  approach | camera | cook | cook food | food | ...

In [52]:
def load_image(path):
    img = Image.open(path).convert("RGB")
    return transform(img).unsqueeze(0)

pred_results = []

for _, row in tqdm(gt_df.iterrows(), total=len(gt_df)):
    img_name = row["file"]
    img_path = os.path.join(image_dir, img_name)

    try:
        img_tensor = load_image(img_path).to(device)

        with torch.no_grad():
            pred_tags = inference_ram_openset(img_tensor, model)

    except:
        pred_tags = ""

    pred_results.append({
        "file": img_name,
        "gt": row["gt"],
        "pred": pred_tags
    })

100%|██████████| 31783/31783 [1:14:25<00:00,  7.12it/s]

In [47]:
img_tensor = load_image(img_path).to(device)
with torch.no_grad():
    pred_tags = inference_ram_openset(img_tensor, model)
print(pred_tags)

boy | couple | garden | person | man | stand | woman | yard

In [53]:
final_df = pd.DataFrame(pred_results)

output_path = "/kaggle/working/flickr30k.csv"
final_df.to_csv(output_path, index=False)

print("Saved to:", output_path)
final_df.head()

Saved to: /kaggle/working/flickr30k.csv

,file,gt,pred
0,1000092795.jpg,enjoy | friend | garden | guy | hair | hand | ...,boy | couple | garden | person | man | stand |...
1,10002456.jpg,equipment | hat | machine | man | on top | ope...,attach | cloudy | construction worker | crane ...
2,1000268201.jpg,ascent | building | cabin | child | dress | en...,shed | chicken coop | child | doll | dress | g...
3,1000344755.jpg,building | clean_and_jerk | hat | jean | ladde...,brick building | building | construction worke...
4,1000366164.jpg,approach | camera | cook | cook food | food | ...,cook | exhaust hood | food | frying pan | home...

# P/R evaluation

In [59]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...

True

In [64]:
import pandas as pd
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

# =========================
# Utils
# =========================
def normalize_tag(tag):
    tag = tag.strip().lower()
    tag = tag.replace("_", " ")
    return tag

def lemma_tag(tag):
    return " ".join([lemmatizer.lemmatize(w) for w in tag.split()])

def get_synonyms(tag):
    """Lấy tập synonym từ WordNet"""
    syns = set()
    for syn in wn.synsets(tag):
        for lemma in syn.lemmas():
            syns.add(lemma.name().replace("_", " "))
    return syns

# def map_gt_to_wordnet(gt_tags):
#     """
#     Với mỗi GT tag:
#     - normalize
#     - lemma
#     - expand synonyms
#     """
#     mapped = set()
#     for tag in gt_tags:
#         tag = normalize_tag(tag)
#         tag = lemma_tag(tag)

#         syns = get_synonyms(tag)
#         if len(syns) > 0:
#             mapped.update(syns)
#         else:
#             mapped.add(tag)

#     return mapped
def map_gt_to_wordnet(gt_tags):
    return set([lemma_tag(normalize_tag(t)) for t in gt_tags])

def parse_tags(tag_str):
    return [t.strip() for t in tag_str.split("|")]

# =========================
# Load data
# =========================
df = pd.read_csv("/kaggle/working/flickr30k.csv")

# =========================
# Compute P/R
# =========================
tp, fp, fn = 0, 0, 0

for _, row in df.iterrows():
    gt_tags = parse_tags(row["gt"])
    pred_tags = parse_tags(row["pred"])

    # normalize pred
    pred_set = set([lemma_tag(normalize_tag(t)) for t in pred_tags])

    # map WordNet cho GT
    gt_set = map_gt_to_wordnet(gt_tags)

    # intersection
    inter = pred_set & gt_set

    tp += len(inter)
    fp += len(pred_set - gt_set)
    fn += len(gt_set - pred_set)

# =========================
# Final metrics
# =========================
precision = tp / (tp + fp + 1e-8)
recall = tp / (tp + fn + 1e-8)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Precision: 0.2823
Recall: 0.2755

# soft match

In [62]:
import pandas as pd
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

# =========================
# Utils
# =========================
def normalize_tag(tag):
    tag = tag.strip().lower()
    tag = tag.replace("_", " ")
    tag = " ".join(tag.split())
    return tag

def lemma_tag(tag):
    return " ".join([lemmatizer.lemmatize(w) for w in tag.split()])

def parse_tags(tag_str):
    return [t.strip() for t in tag_str.split("|")]

# =========================
# Soft match
# =========================
def soft_match(p, gt_set):
    for g in gt_set:
        # exact
        if p == g:
            return True
        # substring
        if p in g or g in p:
            return True
    return False

# =========================
# Load data
# =========================
df = pd.read_csv("/kaggle/working/flickr30k.csv")

# =========================
# Compute P/R (soft match)
# =========================
tp, fp, fn = 0, 0, 0

for _, row in df.iterrows():
    gt_tags = parse_tags(row["gt"])
    pred_tags = parse_tags(row["pred"])

    gt_set = set([lemma_tag(normalize_tag(t)) for t in gt_tags])
    pred_set = set([lemma_tag(normalize_tag(t)) for t in pred_tags])

    matched_gt = set()

    # ---- TP / FP ----
    for p in pred_set:
        found = False
        for g in gt_set:
            if p == g or p in g or g in p:
                tp += 1
                matched_gt.add(g)
                found = True
                break

        if not found:
            fp += 1

    # ---- FN ----
    fn += len(gt_set - matched_gt)

# =========================
# Final metrics
# =========================
precision = tp / (tp + fp + 1e-8)
recall = tp / (tp + fn + 1e-8)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Precision: 0.4215
Recall: 0.3828

# mapping wordnet + exact match

In [63]:
import pandas as pd
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

# =========================
# Utils
# =========================
def normalize_tag(tag):
    tag = tag.strip().lower()
    tag = tag.replace("_", " ")
    tag = " ".join(tag.split())
    return tag

def lemma_tag(tag):
    return " ".join([lemmatizer.lemmatize(w) for w in tag.split()])

def parse_tags(tag_str):
    return [t.strip() for t in tag_str.split("|")]

# =========================
# WordNet mapping
# =========================
def get_synonyms(tag):
    syns = set()
    for syn in wn.synsets(tag):
        for lemma in syn.lemmas():
            syns.add(lemma.name().replace("_", " "))
    return syns

def map_to_wordnet(tags):
    """
    Map mỗi tag → tập synonym
    """
    mapped = set()

    for t in tags:
        t = normalize_tag(t)
        t = lemma_tag(t)

        syns = get_synonyms(t)

        if len(syns) > 0:
            mapped.update(syns)
        else:
            mapped.add(t)

    return mapped

# =========================
# Load data
# =========================
df = pd.read_csv("/kaggle/working/flickr30k.csv")

# =========================
# Compute P/R (WordNet exact)
# =========================
tp, fp, fn = 0, 0, 0

for _, row in df.iterrows():
    gt_tags = parse_tags(row["gt"])
    pred_tags = parse_tags(row["pred"])

    gt_set = map_to_wordnet(gt_tags)
    pred_set = map_to_wordnet(pred_tags)

    # exact match trên synonym space
    inter = pred_set & gt_set

    tp += len(inter)
    fp += len(pred_set - gt_set)
    fn += len(gt_set - pred_set)

# =========================
# Final metrics
# =========================
precision = tp / (tp + fp + 1e-8)
recall = tp / (tp + fn + 1e-8)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Precision: 0.3294
Recall: 0.3663

In [1]:
data = "/kaggle/input/datasets/nguyenbon/ade-20k/ade-20k.csv"

In [2]:
import pandas as pd
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
import nltk

# nếu chưa download wordnet
nltk.download('wordnet')
nltk.download('omw-1.4')

# đọc CSV
df = pd.read_csv(data)

# hàm tách tag
def split_tags(tag_str):
    if pd.isna(tag_str):
        return []
    return [t.strip() for t in tag_str.split("|")]

# khởi tạo lemmatizer
lemmatizer = WordNetLemmatizer()

# map label sang synset
def label_to_synset(label):
    lemma = lemmatizer.lemmatize(label.lower())
    synsets = wn.synsets(lemma)
    if synsets:
        return synsets[0]  # lấy synset đầu tiên
    return None

# lấy danh sách gt label
gt_labels = df["gt"].apply(split_tags)

# flatten và map sang synset
gt_synsets = [label_to_synset(label) for sublist in gt_labels for label in sublist]
gt_synsets = [s for s in gt_synsets if s is not None]  # loại None

# unique synset
gt_unique_synsets = set(gt_synsets)

print("Số class GT sau mapping WordNet:", len(gt_unique_synsets))
print("Một số synset mẫu:", list(gt_unique_synsets)[:20])

[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...

Số class GT sau mapping WordNet: 968
Một số synset mẫu: [Synset('supermarket.n.01'), Synset('display.n.01'), Synset('arbor.n.03'), Synset('section.n.04'), Synset('neck.n.01'), Synset('bowl.n.01'), Synset('counter.n.01'), Synset('palace.n.01'), Synset('dance_school.n.01'), Synset('temple.n.01'), Synset('yard.n.01'), Synset('scale.n.01'), Synset('canopy.n.01'), Synset('irrigation_ditch.n.01'), Synset('business_district.n.01'), Synset('curtain.n.01'), Synset('gallery.n.03'), Synset('estuary.n.01'), Synset('fabric.n.01'), Synset('pat.n.01')]

In [12]:
import pandas as pd
from nltk.stem import WordNetLemmatizer
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')

# đọc CSV
df = pd.read_csv("/kaggle/input/datasets/nguyenbon/ade-20k/ade-20k.csv")

# khởi tạo lemmatizer
lemmatizer = WordNetLemmatizer()

# hàm chuẩn hóa và lemmatize label
def normalize_label(label):
    if not label:
        return ""
    label = label.lower()                 # lowercase
    label = " ".join(label.split())       # chuẩn hóa khoảng trắng
    label = lemmatizer.lemmatize(label)   # lemmatize
    return label

# hàm tách và chuẩn hóa tag
def split_and_normalize(tag_str):
    if pd.isna(tag_str):
        return []
    tags = [normalize_label(t) for t in tag_str.split("|")]
    return tags

# tách tag và chuẩn hóa cho gt và pred
df["gt_tags"] = df["gt"].apply(split_and_normalize)
df["pred_tags"] = df["pred"].apply(split_and_normalize)

# tính Precision/Recall mỗi ảnh
def precision_recall(gt_list, pred_list):
    gt_set = set(gt_list)
    pred_set = set(pred_list)
    if not pred_set:
        precision = 0.0
    else:
        precision = len(gt_set & pred_set) / len(pred_set)
    if not gt_set:
        recall = 0.0
    else:
        recall = len(gt_set & pred_set) / len(gt_set)
    return precision, recall

df["precision"], df["recall"] = zip(*df.apply(lambda row: precision_recall(row["gt_tags"], row["pred_tags"]), axis=1))

# in kết quả trung bình
print("Precision trung bình:", df["precision"].mean())
print("Recall trung bình:", df["recall"].mean())

[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Precision trung bình: 0.2557878489207394
Recall trung bình: 0.20088103149191597

# Val trên Flickr

In [17]:
import os
import json
import pandas as pd
from tqdm import tqdm
from PIL import Image
import torch

# ===== CONFIG =====
json_path = "/kaggle/input/datasets/nguyenbon/trainval-flickr/val.json"
image_dir = "/kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/flickr30k_images"
output_csv = "/kaggle/working/ram_pred.csv"

device = "cuda" if torch.cuda.is_available() else "cpu"

# ===== LOAD JSON =====
with open(json_path, "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# ===== LOAD IMAGE =====
def load_image(path):
    img = Image.open(path).convert("RGB")
    return transform(img).unsqueeze(0)

# ===== INFERENCE =====
pred_results = []

for _, row in tqdm(df.iterrows(), total=len(df)):
    img_name = row["image_path"]
    img_path = os.path.join(image_dir, img_name)

    try:
        img_tensor = load_image(img_path).to(device)

        with torch.no_grad():
            pred_tags = inference_ram_openset(img_tensor, model)

    except Exception as e:
        print(f"Error at {img_name}: {e}")
        pred_tags = ""

    pred_results.append({
        "file": img_name,
        "pred": pred_tags
    })

# ===== SAVE =====
pd.DataFrame(pred_results).to_csv(output_csv, index=False)

print("Saved to:", output_csv)

100%|██████████| 3179/3179 [07:22<00:00,  7.18it/s]

Saved to: /kaggle/working/ram_pred.csv

In [18]:
import pandas as pd
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

# =========================
# Utils
# =========================
def normalize_tag(tag):
    tag = tag.strip().lower()
    tag = tag.replace("_", " ")
    tag = " ".join(tag.split())
    return tag

def lemma_tag(tag):
    return " ".join([lemmatizer.lemmatize(w) for w in tag.split()])

def parse_pipe_tags(tag_str):
    if pd.isna(tag_str):
        return []
    return [t.strip() for t in tag_str.split("|") if t.strip() != ""]

# =========================
# Load data
# =========================
pred_df = pd.read_csv("/kaggle/working/ram_pred.csv")
gt_df = pd.read_csv("/kaggle/input/datasets/nguyenbon/flickr30k/flickr30k.csv")

# chỉ giữ GT
gt_df = gt_df[["file", "gt"]]

# merge
df = pd.merge(pred_df, gt_df, on="file", how="inner")

print(df.columns)  # debug
print("Total samples:", len(df))

# =========================
# Compute P/R
# =========================
tp, fp, fn = 0, 0, 0

for _, row in df.iterrows():
    gt_tags = parse_pipe_tags(row["gt"])
    pred_tags = parse_pipe_tags(row["pred"])

    gt_set = set([lemma_tag(normalize_tag(t)) for t in gt_tags])
    pred_set = set([lemma_tag(normalize_tag(t)) for t in pred_tags])

    inter = pred_set & gt_set

    tp += len(inter)
    fp += len(pred_set - gt_set)
    fn += len(gt_set - pred_set)

# =========================
# Final metrics
# =========================
precision = tp / (tp + fp + 1e-8)
recall = tp / (tp + fn + 1e-8)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Index(['file', 'pred', 'gt'], dtype='object')
Total samples: 3179
Precision: 0.2838
Recall: 0.2766